### ISSUE TITLE
Process "Killed" because OOM for demo_scenegen.py after 'pipeline components' stage

### ISSUE THREAD

**Issue by alkavan** [Tencent-Hunyuan/HunyuanWorld-1.0#6]
Last stage of the process is getting killed because out-of-memory.
Using RTX 6000 (48GB) on a 8 core/64 GB machine, latest ubuntu, drivers, and everything.
It's the same behavior for the text example and for `scripts/test.sh`.
Can the process optimized to fit into 64GB RAM machine? It would be a big cost difference.

```
Jul 27 15:24:00 ml-ai-ubuntu-gpu-6000adax1-48gb-tor1 kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-0.slice/session-5.scope,task=python3,pid=8878,uid=0
Jul 27 15:24:00 ml-ai-ubuntu-gpu-6000adax1-48gb-tor1 kernel: Out of memory: Killed process 8878 (python3) total-vm:117964176kB, anon-rss:64695636kB, file-rss:59820kB, shmem-rss:17064kB, UID:0 pgtables:129676kB oom_score_adj:0
```

Screenshot just before the crash:

<img width="1663" height="571" alt="Image" src="https://github.com/user-attachments/assets/116be363-e34f-47ea-b5f2-6b2726899ed6" />

Terminal output:
```
(HunyuanWorld) root@ml-ai-ubuntu-gpu-6000adax1-48gb-tor1:~/HunyuanWorld-1.0# CUDA_VISIBLE_DEVICES=0 python3 demo_scenegen.py --image_path test_results/case7/panorama.png --classes outdoor --output_path test_results/case7
Output will be saved to: test_results/case7
=============  now loading models ===============
/root/HunyuanWorld-1.0/Real-ESRGAN/realesrgan/utils.py:63: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loadnet = torch.load(model_path, map_location=torch.device('cpu'))
=============  load Super-Resolution models done
=============  load Segmentation models done ====
Loading pipeline components...:   0%|                                                                                                                                                                                                                                                                  | 0/7 [00:00<?, ?it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  9.13it/s]
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.54it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  8.57it/s]
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.36it/s]
Killed
```

If this can be optimized with some parameter, I can test this out.

**Comment by jelling** [comment]
Was it OOM on RAM or VRAM? I also got OOM on 48GB A40 with 50 GB RAm. But I assumed it was VRAM and don't have my error message now. 

Fwiw it worked for me on an A100 80GB.

**Comment by alkavan** [comment]
On the RAM not the VRAM. I have confirmed that it worked with the same VRAM (48GB) and 120GB RAM. I have also confirmed that on the same 64GB machine I had OOM issue if to add another 64GB disk cache it work. That turns to be actually a partial solution for me, but maybe the process can be optimized to take up to 64GB. That could be great allowing more utility.

**Comment by dangerweenie** [comment]
FYI , I found this collab notebook, but after running it i get an error that `bitsandbytes` was not compiled to use GPU , no GPU available.

[Hunyuan-World-1 Collab](https://colab.research.google.com/github/camenduru/HunyuanWorld-1.0-jupyter/blob/main/HunyuanWorld-1.0_jupyter.ipynb)

**Comment by Tolan87** [comment]
> FYI , I found this collab notebook, but after running it i get an error that `bitsandbytes` was not compiled to use GPU , no GPU available.
> 
> [Hunyuan-World-1 Collab](https://colab.research.google.com/github/camenduru/HunyuanWorld-1.0-jupyter/blob/main/HunyuanWorld-1.0_jupyter.ipynb)

I'm not an AI expert, but it's possible the configuration in your linked file is incorrect. 

It uses "CUDA_VISIBLE_DEVICES=1". If your machine only has one GPU, this should be "CUDA_VISIBLE_DEVICES=0" to use the correct GPU. The index starts at 0 (not 1), so '1' would refer to a second GPU.

**Comment by AreebAhmad-02** [comment]
@zhenwwang how can we configure settings to use gpu here?

<img width="956" height="289" alt="Image" src="https://github.com/user-attachments/assets/438d1e4e-4b82-46e5-b8fc-4a4229847762" />

**Comment by jelling** [comment]
@AreebAhmad-02 https://docs.runpod.io/pods/storage/types
